# Generated by Django 2.1.7 on 2019-03-20 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycollections', '0002_auto_20190213_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionTitleChild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Child')),
                ('language', models.CharField(max_length=3)),
                ('collection_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_children', to='mycollections.CollectionTitle')),
            ],
        ),
    ]
